name: openidconnect
description: OpenIdConnect library for flutter.
version: 1.0.22
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  openidconnect_platform_interface: 
    git: 
      url: https://github.com/sherlockvn/openidconnect_interface.git
  openidconnect_web:
    git: 
      url: https://github.com/sherlockvn/openidconnect_web.git

  # openidconnect_windows: ^0.0.6
  flutter_secure_storage: ^5.0.2
  jwt_decoder: ^2.0.1

  cryptography: ^2.0.5

  url_launcher: ^6.0.17
  http: ^0.13.4
  retry: ^3.1.0

  # TODO Remove these once native implementations can be added. Refactor so that the native implementations don't need to do the full cycle through.
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        default_package: openidconnect_web
      # windows:
      #   default_package: openidconnect_windows
